CREATE TABLE PRODUTO (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    PRECO NUMBER(10,2) NOT NULL,
    QUANTIDADE NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_PRODUTO START WITH 1 INCREMENT BY 1;
