
CREATE TABLE PRODUTOS (
                          ID         NUMBER(10)     PRIMARY KEY,
                          NOME       VARCHAR2(100)  NOT NULL,
                          PRECO      NUMBER(12,2)   NOT NULL CHECK (PRECO >= 0),
                          QUANTIDADE NUMBER(10)     DEFAULT 0 NOT NULL CHECK (QUANTIDADE >= 0)
);

CREATE SEQUENCE PRODUTOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE TRIGGER PRODUTOS_BI
BEFORE INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
SELECT PRODUTOS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END IF;
END;
/

CREATE INDEX IDX_PRODUTOS_NOME ON PRODUTOS (UPPER(NOME));
